---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis-storage
  name: redis-storage
spec:
  containers:
  - image: redis:alpine
    name: goat
   # volumeMounts:
   # - mountPath: /data/redis
   #   name: temp-volume
  #volumes:
 # - name: temp-volume
 #   emptyDir: {}